[[main]]
  name = "Transportation"
  url = "/transportation/"
  weight = 10

[[main]]
  name = "Housing & Land Use"
  url = "/housing/"
  weight = 20

[[main]]
  name = "Public Works"
  url = "/public-works/"
  weight = 30

[[main]]
  name = "City Data"
  url = "/city-data/"
  weight = 40

[[main]]
  name = "Maps & Dashboards"
  url = "/maps/"
  weight = 50
