description = "Albuquerque transportation, housing, and transit information database"

[author]
  name = "ABQ Info"

[homepage]
  layout = "page"
  showRecent = false

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = false

[list]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = false
